lms/leave_management/urls.py
from django.urls import path
from . import views

app_name = 'leave_management'

urlpatterns = [
    # path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('leave_form/', views.leave_form, name='leave_form'),
    path('my_leave_record/', views.my_leave_record, name='my_leave_record'),
    path('my_leave_record/<int:pk>/extend_leave', views.extend_leave, name='extend_leave'),
    path('my_leave_record/<int:pk>/extend_approved_leave', views.extend_approved_leave, name='extend_approved_leave'),
    path('leave_structure/', views.leave_structure, name='leave_structure'),


    path('leave_structure/<int:pk>/edit_leave_type/', views.edit_leave_type, name='edit_leave_type'),
    path('leave_structure/<int:pk>/delete_leave_type/', views.delete_leave_type, name='delete_leave_type'),
    path('leave_structure/<int:pk>/edit_holiday/', views.edit_holiday, name='edit_holiday'),
    path('leave_structure/<int:pk>/delete_holiday/', views.delete_holiday, name='delete_holiday'),
    path('leave_structure/<int:pk>/edit_work_week/', views.edit_work_week, name='edit_work_week'),
    path('leave_structure/<int:pk>/delete_work_week/', views.delete_work_week, name='delete_work_week'),

    path('my_leave_balance/', views.my_leave_balance, name='my_leave_balance'),
    path('leave_request/', views.leave_request, name='leave_request'),
    path('ajax-posting/', views.ajax_posting, name='ajax_posting'),
    path('ajax_extend_leave/', views.ajax_extend_leave, name='ajax_extend_leave'),
   

]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
    path('leave_management/', include('leave_management.urls')),
    path('', include('common.urls')),



]

lms/leave_management/models.py
from django.db import models
from django.contrib.auth.models import User
from common.models import User






# Create your models here.


class Leave_type(models.Model):
    leave_name = models.CharField(max_length=100)
    leave_rule = models.CharField(max_length=100, null=True, blank=True)
    leave_per_year = models.CharField(max_length=100, null=True, blank=True)
    leave_carried_forward = models.CharField(max_length=100, null=True, blank=True)
    holiday_name = models.CharField(max_length=100, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    typeleave = models.CharField(max_length=50, default='', blank=True)
    created_by = models.ForeignKey(User, related_name='create_by', on_delete=models.CASCADE, null=True)


class Work_week_plan(models.Model):
    week_day = models.CharField(max_length=100, null=True, blank=True)
    working_off = models.CharField(max_length=50, default=0, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    created_by = models.ForeignKey(User, related_name='create', on_delete=models.CASCADE, null=True)




class My_leave_balance(models.Model):
    leave_name = models.ForeignKey(Leave_type, related_name="leavename", on_delete=models.CASCADE)
    leave_remaining = models.IntegerField(blank=True , default=0)
    created_by = models.ForeignKey(User, related_name='createdby', on_delete=models.CASCADE, null=True)



class Leave_form(models.Model):
    employee_name = models.CharField(max_length=100)
    application_date = models.DateField(auto_now_add=False, blank=True)
    leave_type = models.ForeignKey(Leave_type, related_name="leave_t", on_delete=models.CASCADE)
    remaining_leave = models.IntegerField(blank=True, null=True)
    from_date = models.DateField(auto_now_add=False, blank=True)
    till_date = models.DateField(auto_now_add=False, blank=True)
    total_taken_leave = models.CharField(max_length=100, null=True, blank=True)
    day = models.CharField(max_length=100, null=True, blank=True)
    remark = models.TextField(max_length=2000,blank=True)
    attachment = models.FileField(upload_to='leave_attachment/', null=True, blank=True)
    status = models.CharField(max_length=100, null=True, blank=True)
    created_by = models.ForeignKey(User, related_name='created', on_delete=models.CASCADE, null=True)
    reject_reason = models.CharField(max_length=100, null=True, blank=True)

class Leave_policy(models.Model):
    leave_policy = models.CharField(max_length=2000, blank=True)
    created_by = models.ForeignKey(User, related_name='created_by_leave_policy', on_delete=models.CASCADE, null=True)

lms/leave_management/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import *
from datetime import datetime
from django.http.response import HttpResponseRedirect,HttpResponse
from datetime import date,  timedelta
from django.db.models import Q
from django.http import JsonResponse
import pandas as pd








# Create your views here.

def index(request):
    return render(request, 'leave_management/index.html')

@login_required
def dashboard(request):
    return render(request, 'leave_management/dashboard.html')



 

def leave_form(request):
    leave_type = Leave_type.objects.filter(typeleave='Leave type').distinct()

    leave = My_leave_balance.objects.filter(created_by = request.user.id).values_list('leave_name','leave_remaining')
    if not leave:
        leave = Leave_type.objects.all().values_list('id', 'leave_per_year')
    leave_dict = dict(leave)

    holiday_list = []
    holiday = Leave_type.objects.filter(typeleave='Holiday')
    for i in holiday:
        date_str = str(i.date)
        holiday_list.append(date_str)





    if request.method == 'POST':
        leave_formobj = Leave_form()
        leave_formobj.employee_name     = request.POST.get('employee_name')
        leave_formobj.application_date  = request.POST.get('current_date')
        leave_formobj.leave_type_id     = request.POST.get('leave_type')
        leave_formobj.remaining_leave   = request.POST.get('remaining_leave')
        date_from                       = request.POST.get('from_date')
        leave_formobj.from_date         = datetime.strptime(date_from, "%m/%d/%Y").strftime("%Y-%m-%d")
        date_till                       = request.POST.get('till_date')
        leave_formobj.till_date         = datetime.strptime(date_till, "%m/%d/%Y").strftime("%Y-%m-%d")
        leave_formobj.day               = request.POST.get('day')
        leave_formobj.total_taken_leave = request.POST.get('total_taken_leave')
        leave_formobj.remark            = request.POST.get('remark')
        leave_formobj.attachment        = request.FILES.get('myfile')
        leave_formobj.status            = request.POST.get('status')
        leave_formobj.created_by_id     = request.user.id
        leave_formobj.save()
        return redirect('leave_management:my_leave_record')
    else:
        return render(request,'leave_management/leave_form.html',{'leave_type':leave_type,'leave_dict':leave_dict,'holiday_list':holiday_list})


def my_leave_record(request):
    # date =datetime.now().strftime('%F %d,%Y,')
    # time = datetime.now().strftime('%H')
    # time1 = datetime.strptime('10','%H')
    # t1 = time1.strftime('%H')

    leave_type = Leave_type.objects.filter(typeleave='Leave type').distinct()

    if request.method == 'POST':
        data = request.POST
        if data.get('leave_name'):
            leave_type = Leave_type.objects.filter(leave_type=data.get('leave_type'))


        if data.get('from_date'):
            if data.get('to_date'):
                start_date = data.get('from_date')
                end_date = data.get('to_date')
                leave_form = Leave_form.objects.filter(
                    Q(from_date__gte=start_date) & Q(till_date__lte=end_date)
                )
            else:
                start_date = data.get('from_date')
                end_date = data.get('to_date')
                leave_form = Leave_form.objects.filter(
                    Q(from_date__gte=start_date) & Q(till_date__lte=end_date)
                )

            return render(request,'leave_management/my_leave_record.html', {'leave_form':leave_form,'leave_type':leave_type})

    leave_form = Leave_form.objects.all().order_by('-application_date')
    final_status = Leave_form.objects.filter(id=request.POST.get('withdraw')).first()

    if request.method == 'POST':
        get_leave_type = Leave_type.objects.filter(id=final_status.leave_type.id).first()
        remaining_leave = int(final_status.remaining_leave) + int(final_status.total_taken_leave)
        my_leave_balanceobj = My_leave_balance.objects.filter(leave_name=get_leave_type.id).first()

        final_status.status = 'Withdraw'
        final_status.remaining_leave = remaining_leave
        final_status.save()

        if my_leave_balanceobj:
            my_leave_balanceobj.leave_name_id = get_leave_type.id
            my_leave_balanceobj.leave_remaining = remaining_leave
            my_leave_balanceobj.created_by_id = request.user.id
            my_leave_balanceobj.save()

        return redirect('leave_management:my_leave_record')

    return render(request,'leave_management/my_leave_record.html', {'leave_form':leave_form,'date':date,'leave_type':leave_type})


def extend_leave(request,pk):
    extend_leave = Leave_form.objects.filter(id=pk).first()
    data = {'extend_leave': extend_leave}

    if request.method == 'POST':
        if request.POST['employee_name']:
            extend_leave.employee_name = request.POST["employee_name"]
        if request.POST['current_date']:
            extend_leave.application_date = request.POST['current_date']
        if request.POST['leave_type']:
            extend_leave.leave_type_id = request.POST['leave_type']
        if request.POST['remaining_leave']:
            extend_leave.remaining_leave = request.POST['remaining_leave']
        if request.POST['from_date']:
            date_from = request.POST['from_date']
            extend_leave.from_date=datetime.strptime(date_from, "%m/%d/%Y").strftime("%Y-%m-%d")
        if request.POST['till_date']:
            date_till = request.POST['till_date']
            extend_leave.till_date = datetime.strptime(date_till, "%m/%d/%Y").strftime("%Y-%m-%d")
        if request.POST['total_taken_leave']:
            extend_leave.total_taken_leave = request.POST['total_taken_leave']
        if request.POST['remark']:
            extend_leave.remark = request.POST['remark']
        extend_leave.save()
        return redirect('leave_management:my_leave_record')

    return render(request, 'leave_management/extend_leave.html',data)

def extend_approved_leave(request,pk):
    extend_approved_leave = Leave_form.objects.filter(id=pk).first()
    data = {'extend_approved_leave': extend_approved_leave}

    if request.method == 'POST':
        leave_formobj = Leave_form()
        if request.POST['employee_name']:
            leave_formobj.employee_name = request.POST["employee_name"]
        if request.POST['current_date']:
            leave_formobj.application_date = request.POST['current_date']
        if request.POST['leave_type']:
            leave_formobj.leave_type_id = request.POST['leave_type']
        if request.POST['remaining_leave']:
            leave_formobj.remaining_leave = request.POST['remaining_leave']
        if request.POST['from_date']:
            date_from = request.POST['from_date']
            leave_formobj.from_date=datetime.strptime(date_from, "%m/%d/%Y").strftime("%Y-%m-%d")
        if request.POST['till_date']:
            date_till = request.POST['till_date']
            leave_formobj.till_date = datetime.strptime(date_till, "%m/%d/%Y").strftime("%Y-%m-%d")
        if request.POST['total_taken_leave']:
            leave_formobj.total_taken_leave = request.POST['total_taken_leave']
        if request.POST['remark']:
            leave_formobj.remark = request.POST['remark']
        leave_formobj.attachment = request.FILES.get('myfile')
        leave_formobj.day        = request.POST.get('day')
        leave_formobj.status     = request.POST.get('status')
        leave_formobj.created_by_id = request.user.id
        leave_formobj.save()
        return redirect('leave_management:my_leave_record')

    return render(request,'leave_management/extend_approved_leave.html',data)


def leave_structure(request):

    leave_type   = Leave_type.objects.filter(typeleave = 'Leave type')
    holiday      = Leave_type.objects.filter(typeleave = 'Holiday')
    work_week    = Work_week_plan.objects.all()
    leave_policy = Leave_policy.objects.all()
    
    if request.method == 'POST':
        leave_typeobj = Leave_type()
        if request.POST.get('leave_name'):
            leave_typeobj.typeleave = 'Leave Type'
            leave_typeobj.leave_name = request.POST.get('leave_name')
            leave_typeobj.leave_rule = request.POST.get('leave_rule')
            leave_typeobj.leave_per_year = request.POST.get('leave_per_year')
            leave_typeobj.leave_carried_forward = request.POST.get('leave_carried_forward')
            leave_typeobj.remaining_leave = request.POST.get('leave_per_year')
            leave_typeobj.created_by_id     = request.user.id
            leave_typeobj.save()

        elif request.POST.get('holiday_name'):
            leave_typeobj.typeleave = 'Holiday'
            leave_typeobj.holiday_name = request.POST.get('holiday_name')
            if request.POST['date']:
                leave_typeobj.date = request.POST.get('date')
            if request.POST['holiday_country']:
                leave_typeobj.country = request.POST.get('holiday_country')
            leave_typeobj.created_by_id     = request.user.id
            leave_typeobj.save()

        elif request.POST.get('leave_policy'):
            leave_policyobj = Leave_policy()
            leave_policyobj.leave_policy = request.POST.get('leave_policy')
            leave_policyobj.created_by_id = request.user.id
            leave_policyobj.save()

        else:
            week_list = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
            checkbox_list = request.POST.getlist('checks[]')

            for i in week_list:
                if i in checkbox_list:
                        work_week_planobj = Work_week_plan()
                        work_week_planobj.week_day = i
                        work_week_planobj.working_off = 'Working'

lms/leave_management/templates/leave_management/edit_holiday.html
{% extends 'leave_management/index.html' %}
{% load static %}
{% block content%}


<!--Stylesheet for tab in add leave type-->
<style>
body {font-family: Arial;}

/* Style the tab */
.tab {
  overflow: hidden;
  border: 1px solid #ccc;
  background-color: #f1f1f1;
}

/* Style the buttons inside the tab */
.tab button {
  background-color: inherit;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  transition: 0.3s;
  font-size: 17px;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
  background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
  display: none;
  padding: 6px 12px;
  border: 1px solid #ccc;
  border-top: none;
}
</style>

<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Edit Holiday</h1>
          </div><!-- /.col -->

          <div class="col-sm-6">
<!--            <ol class="breadcrumb float-sm-right">-->
<!--              <li class="breadcrumb-item"><a href="#">Home</a></li>-->
<!--              <li class="breadcrumb-item active"><a href="{% url 'dashboard' %}">Dashboard</a></li>-->
<!--            </ol>-->
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->

    <!-- /.content-header -->



<div class="main_container">
  <div class="row marl">
    <div class="col-md-12">

      <form method="POST" action="{% url 'leave_management:edit_holiday' holiday.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="overview_form_block row marl justify-content-center">
          <div class="col-md-7">
            <div class="card">
              <div class="card-body">
                <div class="card-title text-center">
                  Edit Holiday
                </div><br>
                <div class="row ml-3 mr-3">
                  <div class="col-md-12">
                    <div class="form-group row">
                      <div class="col-md-6">
                        <label for="holiday_name">Holiday Name</label>
						<input type="text" class="form-control" name="holiday_name" id="holiday_name" value="{{holiday.holiday_name}}">
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-6">
                        <label for="date">Date</label>
						<input type="date" onload="getDate()" class="form-control" name="date" id="date"value="{{holiday.date|date:'Y-m-d'}}">
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-6">
                        <label for="country">Country</label>
						<input type="text" class="form-control" name="holiday_country" id="country"  value="{{holiday.country}}">
                      </div>
                    </div>

                      <div class="col-md-12 mt-2">
                        <div class="row marl buttons_row text-center form_btn_row">
                          <button class="btn btn-primary" type="submit">Update</button>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>



</div>

{% endblock %}

lms/leave_management/templates/leave_management/edit_leave_type.html
{% extends 'leave_management/index.html' %}
{% load static %}
{% block content%}


<!--Stylesheet for tab in add leave type-->
<style>
body {font-family: Arial;}

/* Style the tab */
.tab {
  overflow: hidden;
  border: 1px solid #ccc;
  background-color: #f1f1f1;
}

/* Style the buttons inside the tab */
.tab button {
  background-color: inherit;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  transition: 0.3s;
  font-size: 17px;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
  background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
  display: none;
  padding: 6px 12px;
  border: 1px solid #ccc;
  border-top: none;
}
</style>

<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Edit Leave Type</h1>
          </div><!-- /.col -->

          <div class="col-sm-6">
<!--            <ol class="breadcrumb float-sm-right">-->
<!--              <li class="breadcrumb-item"><a href="#">Home</a></li>-->
<!--              <li class="breadcrumb-item active"><a href="{% url 'dashboard' %}">Dashboard</a></li>-->
<!--            </ol>-->
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->

    <!-- /.content-header -->



<div class="main_container">
  <div class="row marl">
    <div class="col-md-12">

      <form method="POST" action="{% url 'leave_management:edit_leave_type' leave_type.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="overview_form_block row marl justify-content-center">
          <div class="col-md-7">
            <div class="card">
              <div class="card-body">
                <div class="card-title text-center">
                  Edit Leave Type
                </div><br>
                <div class="row ml-3 mr-3">
                  <div class="col-md-12">
                    <div class="form-group row">
                      <div class="col-md-6">
                        <label for="leave_name">Leave name</label>
						<input type="text" class="form-control" name="leave_name" id="leave_name" value="{{leave_type.leave_name}}">
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-6">
                        <label for="leave_rule">Leave Rule</label>
						<input type="text" class="form-control" name="leave_rule" id="leave_rule" value="{{leave_type.leave_rule}}">
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-6">
                        <label for="leave_per_year">Leave per Year</label>
						<input type="text" class="form-control" name="leave_per_year" id="leave_per_year" value="{{leave_type.leave_per_year}}">
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-6">
                        <label for="leave_carried_forward">Leave Carried Forward</label>
						<input type="text" class="form-control" name="leave_carried_forward" id="leave_carried_forward" value="{{leave_type.leave_carried_forward}}" >
                      </div>
                    </div>

                      <div class="col-md-12 mt-2">
                        <div class="row marl buttons_row text-center form_btn_row">
                          <button class="btn btn-primary" type="submit">Update</button>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>





</div>

{% endblock %}

lms/leave_management/templates/leave_management/extend_leave.html
{% extends 'leave_management/index.html' %}
{% load static %}
{% block content%}


<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Extend Leave Form</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active"><a href="{% url 'dashboard' %}">Dashboard</a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->

    <!-- /.content-header -->


<form class="needs-validation"   id="leaveForm" method="post" action=" " autocomplete="off" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="form-row">
    <div class="col-md-3 mb-3">
      <label for="validationCustom01">Employee name</label>
      <input type="text" class="form-control" name="employee_name" id="employee_name" placeholder="Employee Name" value="{{extend_leave.employee_name}}" required>

    </div>
      <div class="col-md-3 mb-3">
      <label for="date">Application Date</label>
      <input   class="form-control" id="current_Date" name="current_date" >
      </div>
    </div>

  <div class="form-row">
    <div class="col-md-3 mb-3">
      <label for="leave_type">Leave Type :</label>
      <input  class="form-control" value="{{extend_leave.leave_type.leave_name}}">
      <input type="hidden"  id="leave_type" name="leave_type" class="form-control"  value="{{extend_leave.leave_type_id}}">

    </div>
    <div class="col-md-3 mb-3">
      <label for="remaining_leave">Remaining Leave</label>
      <input type="text" class="form-control" name="remaining_leave" id="remaining_leave" placeholder="Remaining Leave" value="{{extend_leave.remaining_leave}}">
     </div>
  </div>


   <div class="form-row">
     <div class="col-md-3 mb-3">
      <label for="date">From Date</label>
      <input type="text"  class="form-control" id="from_date" name="from_date"  onchange ="daysDifference()" placeholder="mm-dd-yyyy">
    </div>

    <div class="col-md-3 mb-3">
      <label for="date">Till Date</label>
      <input type="text" onload="getDate()" class="form-control" id="till_date" name="till_date" onchange ="daysDifference()" placeholder="mm-dd-yyyy">
    </div>
   </div>
   Total leave applied for days :<h style="color:32A80F" id="result" class="total_taken_leave" name="total_taken_leave"  ></h>
    <div>
        <input type="hidden" name="total_taken_leave" id="total_taken_leave">
	</div>



    <br>
   <div class="col-md-6 mb-3">
       <label for="full_day">Full Day :</label>
       <input type="radio"  name="day" id="full_day" value="1">
       <label for="half_day">Half Day :</label>
       <input type="radio"  name="day" id="half_day" value="0.5">
   </div>



   <div class="form-row">
     <div class="col-md-6 mb-3">
   <label for="remark">Remark</label>

   <input class="form-control" name="remark" id="remark" placeholder="remark" value="{{extend_leave.remark}}" ></input>
     </div>
   </div>
   <div class="form-row">
     <div class="col-md-6 mb-3">
       <label for="myfile">Attachment</label>
       <input type="file" id="myfile" name="myfile" class="form-control" accept="application/pdf">
   </div>
   </div>
   <div>
       <input type="hidden" name="status" value="pending" id="status">
   </div>

      <button class="btn btn-primary" type="submit">Apply</button>
     <a href="" class="btn btn-primary" onclick="window.location.reload">Reset</a>
</form>
</div>

<!--This date is start from 14 days before,from today's date.-->
<script src="https://code.jquery.com/jquery-1.9.1.min.js" integrity="sha256-wS9gmOZBqsqWxgIVgA8Y9WcQOa7PgSIX+rPA0VL2rbQ=" crossorigin="anonymous"></script>
<script>

$(function() {

   $( "#from_date" ).datepicker({minDate: 0});

  });

$(function() {
    $( "#till_date" ).datepicker({minDate: 0});
  });

</script>

<!--This date is start from today's date.(from-date)-->
<script>
/*
   var today = new Date().toISOString().split('T')[0];
    document.getElementsByName("from_date")[0].setAttribute('min', today);
    */
</script>

<!--This date is start from today's date.(till_date)-->
<script>
/*
   var today = new Date().toISOString().split('T')[0];
    document.getElementsByName("till_date")[0].setAttribute('min', today);
    */
</script>



<!--This is a normal datepicker-->
<script>
/*  function getDate(){
    var today = new Date();

document.getElementById("till_date").value = today.getFullYear() + '-' + ('0' + (today.getMonth() + 1)).slice(-2) + '-' + ('0' + today.getDate()).slice(-2);

} */
</script>



<!--For current date -->
<script>
var date = new Date();
var day = date.getDate();
var month = date.getMonth() + 1;
var year = date.getFullYear();

if (month < 10) month = "0" + month;
if (day < 10) day = "0" + day;

var today = year + "-" + month + "-" + day

document.getElementById('current_Date').value = today;

</script>




<!--Day difference between two datapikcer -->
<script>
function daysDifference() {
         //define two variables and fetch the input from HTML form
         var date1 = document.getElementById("from_date").value ;
         var dateI1 = date1.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$1-$2");

         var date2 = document.getElementById("till_date").value;
         var dateI2 = date2.replace(/(\d\d)\/(\d\d)\/(\d{4})/, "$3-$1-$2");

         if (dateI2 != ''){

         $.ajax({
                type : "POST",
                url: "{% url 'leave_management:ajax_posting' %}",
                data: {
                 date1 :dateI1,
                 date2 : dateI2,
                 csrfmiddlewaretoken: '{{ csrf_token }}',
                 dataType: "json",

                },

                success: function(data){
                   document.getElementById("result").innerHTML = data.count ;
                    document.getElementById("total_taken_leave").value = data.count ;
                },

                failure: function() {

                }

            });

         }

         }


</script>





<!--Script for onchange leave type in form so that reamaining leave is display-->
<script>
function LeaveType(leaveval) {


{% for key, value in leave_dict.items %}
if (leaveval == {{key}}) {
  document.getElementById("remaining_leave").value = {{value}};
}
{% endfor%}
};
</script>


{% endblock %}

lms/leave_management/templates/leave_management/footer.html
 <footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.1
    </div>
  </footer>

lms/leave_management/templates/leave_management/header.html
{% load static %}
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-dark navbar-gray-dark p-0">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
<!--      <li class="nav-item d-none d-sm-inline-block">-->
<!--        <a href="{% url 'leave_management:dashboard' %}"  class="nav-link">Dashboard</a>-->
<!--      </li>-->

    </ul>



    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

      <li class="nav-item dropdown show">
        <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="true">
          <i class="fas fa-th-large"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right">

<!--            <a class="dropdown-item" href="/users/list/"><i class="fas fa-users"></i>  <span class="float-right text-muted">Users</span></a>-->
<!--             &lt;!&ndash;<a class="dropdown-item" href="/api/settings/">Settings</a>&ndash;&gt;-->


<!--            <a class="dropdown-item" href="/profile/"><i class="fas fa-user"></i> <span class="float-right text-muted"> Profile</span></a>-->
            <a class="dropdown-item" href="{% url 'login_url' %}" ><i class="fas fa-power-off"></i> <span class="float-right text-muted">Logout</span></a>
        </div>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->